CC = gcc
DEBUG = no
EXE = audioFX
SRC = $(wildcard src/*.c)#Génération de la liste des fichiers sources
OBJ = $(SRC:.c=.o)#Génération de la liste des fichiers objets
LIBS = libportaudio.a -lrt -lm -lasound -ljack -pthread -lSDL -lSDL_ttf #Bibliothèques

ifeq ($(DEBUG), yes)
$(info "Mode debug")
CFLAGS = -g -W -O2
else
$(info "Mode Release")
CFLAGS = -W -O2
endif


all: $(EXE)
$(EXE) : $(OBJ)
	$(CC) -o $@ $^ $(LIBS)


$(OBJ):$(SRC)
	$(CC) -o $@ -c $< $(CFLAGS)
cleanTmp :
	rm -f */*~* #Fichier temporaire d'emacs
	rm -f */*#*
	rm -f *#* *~*

clean : cleanTmp
	rm -f src/*.o

depend:
	makedepend $(SRC)
doc:
	doxygen

